version: "3.8"

services:
  app:
    build: "."
    ports:
      - "5001:5001"
    depends_on:
      - mysqldb
    volumes:
      - ./src:/app/src

  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=thesandbox
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
